baseURL = "https://usl-workshop.github.io/USL-2025-website/"
languageCode = "en"
title = "User-Scheduable Languages Workshop 2025"
theme = "hugo-theme-monochrome"
enableEmoji = true
enableGitInfo = false

[outputs]
home = "HTML"
